package com.devnemo.nemos.vertical.slabs.datagen;

import com.devnemo.nemos.vertical.slabs.tags.VerticalSlabBlockTags;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricTagProvider;
import net.minecraft.core.HolderLookup;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.BlockTags;
import net.minecraft.world.level.block.Block;

import java.util.concurrent.CompletableFuture;

import static com.devnemo.nemos.vertical.slabs.world.level.block.VerticalSlabBlocks.*;

public class BlockTagProvider extends FabricTagProvider.BlockTagProvider {

    public BlockTagProvider(FabricDataOutput output, CompletableFuture<HolderLookup.Provider> providerCompletableFuture) {
        super(output, providerCompletableFuture);
    }

    @Override
    protected void addTags(HolderLookup.Provider provider) {
        getOrCreateRawBuilder(BlockTags.MINEABLE_WITH_AXE)
                .addTag(VerticalSlabBlockTags.WOODEN_VERTICAL_SLABS.location());

        getOrCreateRawBuilder(BlockTags.MINEABLE_WITH_SHOVEL)
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_CATTAIL_THATCH_VERTICAL_SLAB));

        valueLookupBuilder(BlockTags.MINEABLE_WITH_PICKAXE)
                .add(STONE_VERTICAL_SLAB)
                .add(COBBLESTONE_VERTICAL_SLAB)
                .add(MOSSY_COBBLESTONE_VERTICAL_SLAB)
                .add(SMOOTH_STONE_VERTICAL_SLAB)
                .add(STONE_BRICK_VERTICAL_SLAB)
                .add(MOSSY_STONE_BRICK_VERTICAL_SLAB)
                .add(GRANITE_VERTICAL_SLAB)
                .add(POLISHED_GRANITE_VERTICAL_SLAB)
                .add(DIORITE_VERTICAL_SLAB)
                .add(POLISHED_DIORITE_VERTICAL_SLAB)
                .add(ANDESITE_VERTICAL_SLAB)
                .add(POLISHED_ANDESITE_VERTICAL_SLAB)
                .add(COBBLED_DEEPSLATE_VERTICAL_SLAB)
                .add(POLISHED_DEEPSLATE_VERTICAL_SLAB)
                .add(DEEPSLATE_BRICK_VERTICAL_SLAB)
                .add(DEEPSLATE_TILE_VERTICAL_SLAB)
                .add(TUFF_VERTICAL_SLAB)
                .add(POLISHED_TUFF_VERTICAL_SLAB)
                .add(TUFF_BRICK_VERTICAL_SLAB)
                .add(BRICK_VERTICAL_SLAB)
                .add(MUD_BRICK_VERTICAL_SLAB)
                .add(SANDSTONE_VERTICAL_SLAB)
                .add(SMOOTH_SANDSTONE_VERTICAL_SLAB)
                .add(CUT_SANDSTONE_VERTICAL_SLAB)
                .add(RED_SANDSTONE_VERTICAL_SLAB)
                .add(SMOOTH_RED_SANDSTONE_VERTICAL_SLAB)
                .add(CUT_RED_SANDSTONE_VERTICAL_SLAB)
                .add(PRISMARINE_VERTICAL_SLAB)
                .add(PRISMARINE_BRICK_VERTICAL_SLAB)
                .add(DARK_PRISMARINE_VERTICAL_SLAB)
                .add(NETHER_BRICK_VERTICAL_SLAB)
                .add(RED_NETHER_BRICK_VERTICAL_SLAB)
                .add(BLACKSTONE_VERTICAL_SLAB)
                .add(POLISHED_BLACKSTONE_VERTICAL_SLAB)
                .add(POLISHED_BLACKSTONE_BRICK_VERTICAL_SLAB)
                .add(END_STONE_BRICK_VERTICAL_SLAB)
                .add(PURPUR_VERTICAL_SLAB)
                .add(QUARTZ_VERTICAL_SLAB)
                .add(SMOOTH_QUARTZ_VERTICAL_SLAB)
                .add(CUT_COPPER_VERTICAL_SLAB)
                .add(EXPOSED_CUT_COPPER_VERTICAL_SLAB)
                .add(WEATHERED_CUT_COPPER_VERTICAL_SLAB)
                .add(OXIDIZED_CUT_COPPER_VERTICAL_SLAB)
                .add(WAXED_CUT_COPPER_VERTICAL_SLAB)
                .add(WAXED_EXPOSED_CUT_COPPER_VERTICAL_SLAB)
                .add(WAXED_WEATHERED_CUT_COPPER_VERTICAL_SLAB)
                .add(WAXED_OXIDIZED_CUT_COPPER_VERTICAL_SLAB);

        getOrCreateRawBuilder(BlockTags.MINEABLE_WITH_PICKAXE)
                .addOptionalElement(getResourceLocationFromBlockRegistry(MOSSY_STONE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(MOSSY_COBBLED_DEEPSLATE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(MOSSY_DEEPSLATE_BRICK_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(MOSSY_DEEPSLATE_TILE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(MOSSY_TUFF_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(MOSSY_TUFF_BRICK_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(MOSSY_BRICK_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(PALE_MOSSY_STONE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(PALE_MOSSY_COBBLED_DEEPSLATE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(PALE_MOSSY_DEEPSLATE_BRICK_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(PALE_MOSSY_DEEPSLATE_TILE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(PALE_MOSSY_TUFF_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(PALE_MOSSY_TUFF_BRICK_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(PALE_MOSSY_BRICK_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(CRIMSON_MOSSY_STONE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(CRIMSON_MOSSY_COBBLED_DEEPSLATE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(CRIMSON_MOSSY_DEEPSLATE_BRICK_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(CRIMSON_MOSSY_DEEPSLATE_TILE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(CRIMSON_MOSSY_TUFF_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(CRIMSON_MOSSY_TUFF_BRICK_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(CRIMSON_MOSSY_BRICK_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(WARPED_MOSSY_STONE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(WARPED_MOSSY_COBBLED_DEEPSLATE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(WARPED_MOSSY_DEEPSLATE_BRICK_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(WARPED_MOSSY_DEEPSLATE_TILE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(WARPED_MOSSY_TUFF_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(WARPED_MOSSY_TUFF_BRICK_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(WARPED_MOSSY_BRICK_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(CUT_WHITE_SANDSTONE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(SMOOTH_WHITE_SANDSTONE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(WHITE_SANDSTONE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(CUT_ORANGE_SANDSTONE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(SMOOTH_ORANGE_SANDSTONE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(ORANGE_SANDSTONE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(CUT_BLACK_SANDSTONE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(SMOOTH_BLACK_SANDSTONE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BLACK_SANDSTONE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BRIMSTONE_BRICK_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_BLACK_SANDSTONE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_SMOOTH_BLACK_SANDSTONE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_CUT_BLACK_SANDSTONE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_WHITE_SANDSTONE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_SMOOTH_WHITE_SANDSTONE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_CUT_WHITE_SANDSTONE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_BLUE_SANDSTONE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_SMOOTH_BLUE_SANDSTONE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_CUT_BLUE_SANDSTONE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_PURPLE_SANDSTONE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_SMOOTH_PURPLE_SANDSTONE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_CUT_PURPLE_SANDSTONE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_PINK_SANDSTONE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_SMOOTH_PINK_SANDSTONE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_CUT_PINK_SANDSTONE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_WINDSWEPT_SANDSTONE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_SMOOTH_WINDSWEPT_SANDSTONE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_CUT_WINDSWEPT_SANDSTONE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_DACITE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_DACITE_BRICK_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_CRACKED_DACITE_BRICK_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_MOSSY_DACITE_BRICK_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_CHISELED_DACITE_BRICK_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_DACITE_COBBLESTONE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_DACITE_TILE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_WHITE_DACITE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_WHITE_DACITE_BRICK_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_CRACKED_WHITE_DACITE_BRICK_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_MOSSY_WHITE_DACITE_BRICK_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_CHISELED_WHITE_DACITE_BRICK_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_WHITE_DACITE_COBBLESTONE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_WHITE_DACITE_TILE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_RED_ROCK_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_RED_ROCK_BRICK_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_CRACKED_RED_ROCK_BRICK_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_MOSSY_RED_ROCK_BRICK_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_CHISELED_RED_ROCK_BRICK_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_POLISHED_RED_ROCK_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_RED_ROCK_TILE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_MOSSY_STONE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_ROCKY_STONE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_PALE_MUD_BRICK_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_CATTAIL_THATCH_VERTICAL_SLAB));

        getOrCreateRawBuilder(VerticalSlabBlockTags.WOODEN_VERTICAL_SLABS)
                .addElement(getResourceLocationFromBlockRegistry(OAK_VERTICAL_SLAB))
                .addElement(getResourceLocationFromBlockRegistry(SPRUCE_VERTICAL_SLAB))
                .addElement(getResourceLocationFromBlockRegistry(BIRCH_VERTICAL_SLAB))
                .addElement(getResourceLocationFromBlockRegistry(JUNGLE_VERTICAL_SLAB))
                .addElement(getResourceLocationFromBlockRegistry(ACACIA_VERTICAL_SLAB))
                .addElement(getResourceLocationFromBlockRegistry(DARK_OAK_VERTICAL_SLAB))
                .addElement(getResourceLocationFromBlockRegistry(PALE_OAK_VERTICAL_SLAB))
                .addElement(getResourceLocationFromBlockRegistry(CRIMSON_VERTICAL_SLAB))
                .addElement(getResourceLocationFromBlockRegistry(WARPED_VERTICAL_SLAB))
                .addElement(getResourceLocationFromBlockRegistry(MANGROVE_VERTICAL_SLAB))
                .addElement(getResourceLocationFromBlockRegistry(BAMBOO_VERTICAL_SLAB))
                .addElement(getResourceLocationFromBlockRegistry(CHERRY_VERTICAL_SLAB))

                .addOptionalElement(getResourceLocationFromBlockRegistry(MOSSY_OAK_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(MOSSY_SPRUCE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(MOSSY_BIRCH_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(MOSSY_JUNGLE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(MOSSY_ACACIA_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(MOSSY_DARK_OAK_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(MOSSY_PALE_OAK_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(MOSSY_CRIMSON_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(MOSSY_WARPED_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(MOSSY_MANGROVE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(MOSSY_BAMBOO_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(MOSSY_CHERRY_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(PALE_MOSSY_OAK_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(PALE_MOSSY_SPRUCE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(PALE_MOSSY_BIRCH_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(PALE_MOSSY_JUNGLE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(PALE_MOSSY_ACACIA_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(PALE_MOSSY_DARK_OAK_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(PALE_MOSSY_PALE_OAK_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(PALE_MOSSY_CRIMSON_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(PALE_MOSSY_WARPED_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(PALE_MOSSY_MANGROVE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(PALE_MOSSY_BAMBOO_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(PALE_MOSSY_CHERRY_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(CRIMSON_MOSSY_OAK_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(CRIMSON_MOSSY_SPRUCE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(CRIMSON_MOSSY_BIRCH_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(CRIMSON_MOSSY_JUNGLE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(CRIMSON_MOSSY_ACACIA_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(CRIMSON_MOSSY_DARK_OAK_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(CRIMSON_MOSSY_PALE_OAK_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(CRIMSON_MOSSY_CRIMSON_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(CRIMSON_MOSSY_WARPED_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(CRIMSON_MOSSY_MANGROVE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(CRIMSON_MOSSY_BAMBOO_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(CRIMSON_MOSSY_CHERRY_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(WARPED_MOSSY_OAK_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(WARPED_MOSSY_SPRUCE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(WARPED_MOSSY_BIRCH_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(WARPED_MOSSY_JUNGLE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(WARPED_MOSSY_ACACIA_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(WARPED_MOSSY_DARK_OAK_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(WARPED_MOSSY_PALE_OAK_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(WARPED_MOSSY_CRIMSON_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(WARPED_MOSSY_WARPED_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(WARPED_MOSSY_MANGROVE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(WARPED_MOSSY_BAMBOO_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(WARPED_MOSSY_CHERRY_VERTICAL_SLAB))

                .addOptionalElement(getResourceLocationFromBlockRegistry(FIR_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(PINE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(MAPLE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(REDWOOD_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(MAHOGANY_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(JACARANDA_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(PALM_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(WILLOW_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(DEAD_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(UMBRAN_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(HELLBARK_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(EMPYREAL_VERTICAL_SLAB))

                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_ASPEN_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_BOABAB_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_BLUE_ENCHANTED_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_CIKA_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_CYPRESS_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_EBONY_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_FIR_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_FLORUS_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_GREEN_ENCHANTED_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_HOLLY_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_IRONWOOD_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_JACARANDA_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_MAHOGANY_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_MAPLE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_PALM_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_PINE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_RAINBOW_EUCALYPTUS_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_REDWOOD_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_SAKURA_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_SKYRIS_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_SPIRIT_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_WHITE_MANGROVE_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_WILLOW_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_WITCH_HAZEL_VERTICAL_SLAB))
                .addOptionalElement(getResourceLocationFromBlockRegistry(BIOMES_WEVE_GONE_ZELKOVA_VERTICAL_SLAB));
    }

    private ResourceLocation getResourceLocationFromBlockRegistry(Block block) {
        return BuiltInRegistries.BLOCK.getKey(block);
    }
}
