package com.devnemo.nemos.vertical.slabs.world.item;

import com.devnemo.nemos.vertical.slabs.world.level.block.VerticalSlabBlocks;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.block.Block;

public class VerticalSlabItems {

    public static final Item OAK_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.OAK_VERTICAL_SLAB);
    public static final Item SPRUCE_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.SPRUCE_VERTICAL_SLAB);
    public static final Item BIRCH_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.BIRCH_VERTICAL_SLAB);
    public static final Item JUNGLE_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.JUNGLE_VERTICAL_SLAB);
    public static final Item ACACIA_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.ACACIA_VERTICAL_SLAB);
    public static final Item DARK_OAK_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.DARK_OAK_VERTICAL_SLAB);
    public static final Item MANGROVE_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.MANGROVE_VERTICAL_SLAB);
    public static final Item CHERRY_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.CHERRY_VERTICAL_SLAB);
    public static final Item PALE_OAK_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.PALE_OAK_VERTICAL_SLAB);
    public static final Item BAMBOO_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.BAMBOO_VERTICAL_SLAB);
    public static final Item BAMBOO_MOSAIC_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.BAMBOO_MOSAIC_VERTICAL_SLAB);
    public static final Item CRIMSON_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.CRIMSON_VERTICAL_SLAB);
    public static final Item WARPED_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.WARPED_VERTICAL_SLAB);
    public static final Item STONE_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.STONE_VERTICAL_SLAB);
    public static final Item COBBLESTONE_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.COBBLESTONE_VERTICAL_SLAB);
    public static final Item MOSSY_COBBLESTONE_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.MOSSY_COBBLESTONE_VERTICAL_SLAB);
    public static final Item SMOOTH_STONE_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.SMOOTH_STONE_VERTICAL_SLAB);
    public static final Item STONE_BRICK_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.STONE_BRICK_VERTICAL_SLAB);
    public static final Item MOSSY_STONE_BRICK_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.MOSSY_STONE_BRICK_VERTICAL_SLAB);
    public static final Item GRANITE_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.GRANITE_VERTICAL_SLAB);
    public static final Item POLISHED_GRANITE_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.POLISHED_GRANITE_VERTICAL_SLAB);
    public static final Item DIORITE_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.DIORITE_VERTICAL_SLAB);
    public static final Item POLISHED_DIORITE_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.POLISHED_DIORITE_VERTICAL_SLAB);
    public static final Item ANDESITE_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.ANDESITE_VERTICAL_SLAB);
    public static final Item POLISHED_ANDESITE_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.POLISHED_ANDESITE_VERTICAL_SLAB);
    public static final Item COBBLED_DEEPSLATE_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.COBBLED_DEEPSLATE_VERTICAL_SLAB);
    public static final Item POLISHED_DEEPSLATE_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.POLISHED_DEEPSLATE_VERTICAL_SLAB);
    public static final Item DEEPSLATE_BRICK_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.DEEPSLATE_BRICK_VERTICAL_SLAB);
    public static final Item DEEPSLATE_TILE_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.DEEPSLATE_TILE_VERTICAL_SLAB);
    public static final Item TUFF_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.TUFF_VERTICAL_SLAB);
    public static final Item POLISHED_TUFF_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.POLISHED_TUFF_VERTICAL_SLAB);
    public static final Item TUFF_BRICK_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.TUFF_BRICK_VERTICAL_SLAB);
    public static final Item BRICK_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.BRICK_VERTICAL_SLAB);
    public static final Item MUD_BRICK_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.MUD_BRICK_VERTICAL_SLAB);
    public static final Item SANDSTONE_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.SANDSTONE_VERTICAL_SLAB);
    public static final Item SMOOTH_SANDSTONE_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.SMOOTH_SANDSTONE_VERTICAL_SLAB);
    public static final Item CUT_SANDSTONE_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.CUT_SANDSTONE_VERTICAL_SLAB);
    public static final Item RED_SANDSTONE_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.RED_SANDSTONE_VERTICAL_SLAB);
    public static final Item SMOOTH_RED_SANDSTONE_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.SMOOTH_RED_SANDSTONE_VERTICAL_SLAB);
    public static final Item CUT_RED_SANDSTONE_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.CUT_RED_SANDSTONE_VERTICAL_SLAB);
    public static final Item PRISMARINE_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.PRISMARINE_VERTICAL_SLAB);
    public static final Item PRISMARINE_BRICK_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.PRISMARINE_BRICK_VERTICAL_SLAB);
    public static final Item DARK_PRISMARINE_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.DARK_PRISMARINE_VERTICAL_SLAB);
    public static final Item NETHER_BRICK_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.NETHER_BRICK_VERTICAL_SLAB);
    public static final Item RED_NETHER_BRICK_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.RED_NETHER_BRICK_VERTICAL_SLAB);
    public static final Item BLACKSTONE_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.BLACKSTONE_VERTICAL_SLAB);
    public static final Item POLISHED_BLACKSTONE_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.POLISHED_BLACKSTONE_VERTICAL_SLAB);
    public static final Item POLISHED_BLACKSTONE_BRICK_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.POLISHED_BLACKSTONE_BRICK_VERTICAL_SLAB);
    public static final Item END_STONE_BRICK_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.END_STONE_BRICK_VERTICAL_SLAB);
    public static final Item PURPUR_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.PURPUR_VERTICAL_SLAB);
    public static final Item QUARTZ_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.QUARTZ_VERTICAL_SLAB);
    public static final Item SMOOTH_QUARTZ_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.SMOOTH_QUARTZ_VERTICAL_SLAB);
    public static final Item CUT_COPPER_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.CUT_COPPER_VERTICAL_SLAB);
    public static final Item EXPOSED_CUT_COPPER_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.EXPOSED_CUT_COPPER_VERTICAL_SLAB);
    public static final Item WEATHERED_CUT_COPPER_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.WEATHERED_CUT_COPPER_VERTICAL_SLAB);
    public static final Item OXIDIZED_CUT_COPPER_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.OXIDIZED_CUT_COPPER_VERTICAL_SLAB);
    public static final Item WAXED_CUT_COPPER_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.WAXED_CUT_COPPER_VERTICAL_SLAB);
    public static final Item WAXED_EXPOSED_CUT_COPPER_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.WAXED_EXPOSED_CUT_COPPER_VERTICAL_SLAB);
    public static final Item WAXED_WEATHERED_CUT_COPPER_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.WAXED_WEATHERED_CUT_COPPER_VERTICAL_SLAB);
    public static final Item WAXED_OXIDIZED_CUT_COPPER_VERTICAL_SLAB = Items.registerBlock(VerticalSlabBlocks.WAXED_OXIDIZED_CUT_COPPER_VERTICAL_SLAB);

    public static final Item MOSSY_OAK_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.MOSSY_OAK_VERTICAL_SLAB);
    public static final Item MOSSY_SPRUCE_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.MOSSY_SPRUCE_VERTICAL_SLAB);
    public static final Item MOSSY_BIRCH_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.MOSSY_BIRCH_VERTICAL_SLAB);
    public static final Item MOSSY_JUNGLE_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.MOSSY_JUNGLE_VERTICAL_SLAB);
    public static final Item MOSSY_ACACIA_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.MOSSY_ACACIA_VERTICAL_SLAB);
    public static final Item MOSSY_DARK_OAK_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.MOSSY_DARK_OAK_VERTICAL_SLAB);
    public static final Item MOSSY_MANGROVE_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.MOSSY_MANGROVE_VERTICAL_SLAB);
    public static final Item MOSSY_CHERRY_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.MOSSY_CHERRY_VERTICAL_SLAB);
    public static final Item MOSSY_PALE_OAK_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.MOSSY_PALE_OAK_VERTICAL_SLAB);
    public static final Item MOSSY_BAMBOO_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.MOSSY_BAMBOO_VERTICAL_SLAB);
    public static final Item MOSSY_BAMBOO_MOSAIC_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.MOSSY_BAMBOO_MOSAIC_VERTICAL_SLAB);
    public static final Item MOSSY_CRIMSON_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.MOSSY_CRIMSON_VERTICAL_SLAB);
    public static final Item MOSSY_WARPED_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.MOSSY_WARPED_VERTICAL_SLAB);
    public static final Item MOSSY_STONE_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.MOSSY_STONE_VERTICAL_SLAB);
    public static final Item MOSSY_BRICK_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.MOSSY_BRICK_VERTICAL_SLAB);
    public static final Item MOSSY_COBBLED_DEEPSLATE_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.MOSSY_COBBLED_DEEPSLATE_VERTICAL_SLAB);
    public static final Item MOSSY_DEEPSLATE_BRICK_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.MOSSY_DEEPSLATE_BRICK_VERTICAL_SLAB);
    public static final Item MOSSY_DEEPSLATE_TILE_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.MOSSY_DEEPSLATE_TILE_VERTICAL_SLAB);
    public static final Item MOSSY_TUFF_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.MOSSY_TUFF_VERTICAL_SLAB);
    public static final Item MOSSY_TUFF_BRICK_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.MOSSY_TUFF_BRICK_VERTICAL_SLAB);
    public static final Item PALE_MOSSY_OAK_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.PALE_MOSSY_OAK_VERTICAL_SLAB);
    public static final Item PALE_MOSSY_SPRUCE_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.PALE_MOSSY_SPRUCE_VERTICAL_SLAB);
    public static final Item PALE_MOSSY_BIRCH_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.PALE_MOSSY_BIRCH_VERTICAL_SLAB);
    public static final Item PALE_MOSSY_JUNGLE_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.PALE_MOSSY_JUNGLE_VERTICAL_SLAB);
    public static final Item PALE_MOSSY_ACACIA_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.PALE_MOSSY_ACACIA_VERTICAL_SLAB);
    public static final Item PALE_MOSSY_DARK_OAK_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.PALE_MOSSY_DARK_OAK_VERTICAL_SLAB);
    public static final Item PALE_MOSSY_MANGROVE_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.PALE_MOSSY_MANGROVE_VERTICAL_SLAB);
    public static final Item PALE_MOSSY_CHERRY_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.PALE_MOSSY_CHERRY_VERTICAL_SLAB);
    public static final Item PALE_MOSSY_PALE_OAK_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.PALE_MOSSY_PALE_OAK_VERTICAL_SLAB);
    public static final Item PALE_MOSSY_BAMBOO_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.PALE_MOSSY_BAMBOO_VERTICAL_SLAB);
    public static final Item PALE_MOSSY_BAMBOO_MOSAIC_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.PALE_MOSSY_BAMBOO_MOSAIC_VERTICAL_SLAB);
    public static final Item PALE_MOSSY_CRIMSON_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.PALE_MOSSY_CRIMSON_VERTICAL_SLAB);
    public static final Item PALE_MOSSY_WARPED_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.PALE_MOSSY_WARPED_VERTICAL_SLAB);
    public static final Item PALE_MOSSY_STONE_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.PALE_MOSSY_STONE_VERTICAL_SLAB);
    public static final Item PALE_MOSSY_BRICK_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.PALE_MOSSY_BRICK_VERTICAL_SLAB);
    public static final Item PALE_MOSSY_COBBLED_DEEPSLATE_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.PALE_MOSSY_COBBLED_DEEPSLATE_VERTICAL_SLAB);
    public static final Item PALE_MOSSY_DEEPSLATE_BRICK_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.PALE_MOSSY_DEEPSLATE_BRICK_VERTICAL_SLAB);
    public static final Item PALE_MOSSY_DEEPSLATE_TILE_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.PALE_MOSSY_DEEPSLATE_TILE_VERTICAL_SLAB);
    public static final Item PALE_MOSSY_TUFF_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.PALE_MOSSY_TUFF_VERTICAL_SLAB);
    public static final Item PALE_MOSSY_TUFF_BRICK_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.PALE_MOSSY_TUFF_BRICK_VERTICAL_SLAB);
    public static final Item CRIMSON_MOSSY_OAK_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.CRIMSON_MOSSY_OAK_VERTICAL_SLAB);
    public static final Item CRIMSON_MOSSY_SPRUCE_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.CRIMSON_MOSSY_SPRUCE_VERTICAL_SLAB);
    public static final Item CRIMSON_MOSSY_BIRCH_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.CRIMSON_MOSSY_BIRCH_VERTICAL_SLAB);
    public static final Item CRIMSON_MOSSY_JUNGLE_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.CRIMSON_MOSSY_JUNGLE_VERTICAL_SLAB);
    public static final Item CRIMSON_MOSSY_ACACIA_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.CRIMSON_MOSSY_ACACIA_VERTICAL_SLAB);
    public static final Item CRIMSON_MOSSY_DARK_OAK_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.CRIMSON_MOSSY_DARK_OAK_VERTICAL_SLAB);
    public static final Item CRIMSON_MOSSY_MANGROVE_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.CRIMSON_MOSSY_MANGROVE_VERTICAL_SLAB);
    public static final Item CRIMSON_MOSSY_CHERRY_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.CRIMSON_MOSSY_CHERRY_VERTICAL_SLAB);
    public static final Item CRIMSON_MOSSY_PALE_OAK_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.CRIMSON_MOSSY_PALE_OAK_VERTICAL_SLAB);
    public static final Item CRIMSON_MOSSY_BAMBOO_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.CRIMSON_MOSSY_BAMBOO_VERTICAL_SLAB);
    public static final Item CRIMSON_MOSSY_BAMBOO_MOSAIC_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.CRIMSON_MOSSY_BAMBOO_MOSAIC_VERTICAL_SLAB);
    public static final Item CRIMSON_MOSSY_CRIMSON_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.CRIMSON_MOSSY_CRIMSON_VERTICAL_SLAB);
    public static final Item CRIMSON_MOSSY_WARPED_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.CRIMSON_MOSSY_WARPED_VERTICAL_SLAB);
    public static final Item CRIMSON_MOSSY_STONE_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.CRIMSON_MOSSY_STONE_VERTICAL_SLAB);
    public static final Item CRIMSON_MOSSY_BRICK_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.CRIMSON_MOSSY_BRICK_VERTICAL_SLAB);
    public static final Item CRIMSON_MOSSY_COBBLED_DEEPSLATE_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.CRIMSON_MOSSY_COBBLED_DEEPSLATE_VERTICAL_SLAB);
    public static final Item CRIMSON_MOSSY_DEEPSLATE_BRICK_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.CRIMSON_MOSSY_DEEPSLATE_BRICK_VERTICAL_SLAB);
    public static final Item CRIMSON_MOSSY_DEEPSLATE_TILE_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.CRIMSON_MOSSY_DEEPSLATE_TILE_VERTICAL_SLAB);
    public static final Item CRIMSON_MOSSY_TUFF_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.CRIMSON_MOSSY_TUFF_VERTICAL_SLAB);
    public static final Item CRIMSON_MOSSY_TUFF_BRICK_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.CRIMSON_MOSSY_TUFF_BRICK_VERTICAL_SLAB);
    public static final Item WARPED_MOSSY_OAK_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.WARPED_MOSSY_OAK_VERTICAL_SLAB);
    public static final Item WARPED_MOSSY_SPRUCE_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.WARPED_MOSSY_SPRUCE_VERTICAL_SLAB);
    public static final Item WARPED_MOSSY_BIRCH_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.WARPED_MOSSY_BIRCH_VERTICAL_SLAB);
    public static final Item WARPED_MOSSY_JUNGLE_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.WARPED_MOSSY_JUNGLE_VERTICAL_SLAB);
    public static final Item WARPED_MOSSY_ACACIA_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.WARPED_MOSSY_ACACIA_VERTICAL_SLAB);
    public static final Item WARPED_MOSSY_DARK_OAK_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.WARPED_MOSSY_DARK_OAK_VERTICAL_SLAB);
    public static final Item WARPED_MOSSY_MANGROVE_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.WARPED_MOSSY_MANGROVE_VERTICAL_SLAB);
    public static final Item WARPED_MOSSY_CHERRY_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.WARPED_MOSSY_CHERRY_VERTICAL_SLAB);
    public static final Item WARPED_MOSSY_PALE_OAK_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.WARPED_MOSSY_PALE_OAK_VERTICAL_SLAB);
    public static final Item WARPED_MOSSY_BAMBOO_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.WARPED_MOSSY_BAMBOO_VERTICAL_SLAB);
    public static final Item WARPED_MOSSY_BAMBOO_MOSAIC_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.WARPED_MOSSY_BAMBOO_MOSAIC_VERTICAL_SLAB);
    public static final Item WARPED_MOSSY_CRIMSON_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.WARPED_MOSSY_CRIMSON_VERTICAL_SLAB);
    public static final Item WARPED_MOSSY_WARPED_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.WARPED_MOSSY_WARPED_VERTICAL_SLAB);
    public static final Item WARPED_MOSSY_STONE_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.WARPED_MOSSY_STONE_VERTICAL_SLAB);
    public static final Item WARPED_MOSSY_BRICK_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.WARPED_MOSSY_BRICK_VERTICAL_SLAB);
    public static final Item WARPED_MOSSY_COBBLED_DEEPSLATE_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.WARPED_MOSSY_COBBLED_DEEPSLATE_VERTICAL_SLAB);
    public static final Item WARPED_MOSSY_DEEPSLATE_BRICK_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.WARPED_MOSSY_DEEPSLATE_BRICK_VERTICAL_SLAB);
    public static final Item WARPED_MOSSY_DEEPSLATE_TILE_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.WARPED_MOSSY_DEEPSLATE_TILE_VERTICAL_SLAB);
    public static final Item WARPED_MOSSY_TUFF_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.WARPED_MOSSY_TUFF_VERTICAL_SLAB);
    public static final Item WARPED_MOSSY_TUFF_BRICK_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.WARPED_MOSSY_TUFF_BRICK_VERTICAL_SLAB);

    public static final Item CUT_WHITE_SANDSTONE_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.CUT_WHITE_SANDSTONE_VERTICAL_SLAB);
    public static final Item SMOOTH_WHITE_SANDSTONE_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.SMOOTH_WHITE_SANDSTONE_VERTICAL_SLAB);
    public static final Item WHITE_SANDSTONE_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.WHITE_SANDSTONE_VERTICAL_SLAB);
    public static final Item CUT_ORANGE_SANDSTONE_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.CUT_ORANGE_SANDSTONE_VERTICAL_SLAB);
    public static final Item SMOOTH_ORANGE_SANDSTONE_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.SMOOTH_ORANGE_SANDSTONE_VERTICAL_SLAB);
    public static final Item ORANGE_SANDSTONE_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.ORANGE_SANDSTONE_VERTICAL_SLAB);
    public static final Item CUT_BLACK_SANDSTONE_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.CUT_BLACK_SANDSTONE_VERTICAL_SLAB);
    public static final Item SMOOTH_BLACK_SANDSTONE_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.SMOOTH_BLACK_SANDSTONE_VERTICAL_SLAB);
    public static final Item BLACK_SANDSTONE_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.BLACK_SANDSTONE_VERTICAL_SLAB);
    public static final Item BRIMSTONE_BRICK_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.BRIMSTONE_BRICK_VERTICAL_SLAB);
    public static final Item FIR_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.FIR_VERTICAL_SLAB);
    public static final Item PINE_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.PINE_VERTICAL_SLAB);
    public static final Item MAPLE_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.MAPLE_VERTICAL_SLAB);
    public static final Item REDWOOD_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.REDWOOD_VERTICAL_SLAB);
    public static final Item MAHOGANY_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.MAHOGANY_VERTICAL_SLAB);
    public static final Item JACARANDA_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.JACARANDA_VERTICAL_SLAB);
    public static final Item PALM_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.PALM_VERTICAL_SLAB);
    public static final Item WILLOW_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.WILLOW_VERTICAL_SLAB);
    public static final Item DEAD_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.DEAD_VERTICAL_SLAB);
    public static final Item MAGIC_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.MAGIC_VERTICAL_SLAB);
    public static final Item UMBRAN_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.UMBRAN_VERTICAL_SLAB);
    public static final Item HELLBARK_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.HELLBARK_VERTICAL_SLAB);
    public static final Item EMPYREAL_VERTICAL_SLAB = registerNullableBlock(VerticalSlabBlocks.EMPYREAL_VERTICAL_SLAB);
    
    public static void init() {}

    private static Item registerNullableBlock(Block block) {
        if (block == null) {
            return null;
        }

        return Items.registerBlock(block);
    }
}
