package com.devnemo.nemos.vertical.slabs.datagen;

import com.devnemo.nemos.vertical.slabs.world.level.block.VerticalSlabBlocks;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricTagProvider;
import net.minecraft.core.HolderLookup;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.BlockTags;
import net.minecraft.world.level.block.Block;

import java.util.concurrent.CompletableFuture;

public class BlockTagProvider extends FabricTagProvider.BlockTagProvider {

    public BlockTagProvider(FabricDataOutput output, CompletableFuture<HolderLookup.Provider> providerCompletableFuture) {
        super(output, providerCompletableFuture);
    }

    @Override
    protected void addTags(HolderLookup.Provider provider) {
        valueLookupBuilder(BlockTags.MINEABLE_WITH_AXE)
                .add(VerticalSlabBlocks.OAK_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.SPRUCE_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.BIRCH_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.JUNGLE_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.ACACIA_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.DARK_OAK_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.MANGROVE_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.CHERRY_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.PALE_OAK_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.BAMBOO_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.BAMBOO_MOSAIC_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.CRIMSON_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.WARPED_VERTICAL_SLAB.get());

        getOrCreateRawBuilder(BlockTags.MINEABLE_WITH_AXE)
                .addOptionalElement(BuiltInRegistries.BLOCK.getKey(VerticalSlabBlocks.MOSSY_OAK_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.MOSSY_SPRUCE_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.MOSSY_BIRCH_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.MOSSY_JUNGLE_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.MOSSY_ACACIA_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.MOSSY_DARK_OAK_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.MOSSY_MANGROVE_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.MOSSY_CHERRY_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.MOSSY_PALE_OAK_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.MOSSY_BAMBOO_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.MOSSY_BAMBOO_MOSAIC_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.MOSSY_CRIMSON_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.MOSSY_WARPED_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.PALE_MOSSY_OAK_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.PALE_MOSSY_SPRUCE_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.PALE_MOSSY_BIRCH_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.PALE_MOSSY_JUNGLE_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.PALE_MOSSY_ACACIA_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.PALE_MOSSY_DARK_OAK_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.PALE_MOSSY_MANGROVE_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.PALE_MOSSY_CHERRY_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.PALE_MOSSY_PALE_OAK_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.PALE_MOSSY_BAMBOO_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.PALE_MOSSY_BAMBOO_MOSAIC_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.PALE_MOSSY_CRIMSON_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.PALE_MOSSY_WARPED_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.CRIMSON_MOSSY_OAK_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.CRIMSON_MOSSY_SPRUCE_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.CRIMSON_MOSSY_BIRCH_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.CRIMSON_MOSSY_JUNGLE_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.CRIMSON_MOSSY_ACACIA_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.CRIMSON_MOSSY_DARK_OAK_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.CRIMSON_MOSSY_MANGROVE_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.CRIMSON_MOSSY_CHERRY_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.CRIMSON_MOSSY_PALE_OAK_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.CRIMSON_MOSSY_BAMBOO_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.CRIMSON_MOSSY_BAMBOO_MOSAIC_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.CRIMSON_MOSSY_CRIMSON_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.CRIMSON_MOSSY_WARPED_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.WARPED_MOSSY_OAK_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.WARPED_MOSSY_SPRUCE_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.WARPED_MOSSY_BIRCH_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.WARPED_MOSSY_JUNGLE_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.WARPED_MOSSY_ACACIA_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.WARPED_MOSSY_DARK_OAK_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.WARPED_MOSSY_MANGROVE_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.WARPED_MOSSY_CHERRY_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.WARPED_MOSSY_PALE_OAK_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.WARPED_MOSSY_BAMBOO_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.WARPED_MOSSY_BAMBOO_MOSAIC_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.WARPED_MOSSY_CRIMSON_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.WARPED_MOSSY_WARPED_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.FIR_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.PINE_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.MAPLE_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.REDWOOD_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.MAHOGANY_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.JACARANDA_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.PALM_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.WILLOW_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.DEAD_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.MAGIC_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.UMBRAN_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.HELLBARK_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.EMPYREAL_VERTICAL_SLAB.get()));

        valueLookupBuilder(BlockTags.MINEABLE_WITH_PICKAXE)
                .add(VerticalSlabBlocks.STONE_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.COBBLESTONE_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.MOSSY_COBBLESTONE_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.SMOOTH_STONE_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.STONE_BRICK_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.MOSSY_STONE_BRICK_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.GRANITE_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.POLISHED_GRANITE_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.DIORITE_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.POLISHED_DIORITE_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.ANDESITE_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.POLISHED_ANDESITE_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.COBBLED_DEEPSLATE_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.POLISHED_DEEPSLATE_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.DEEPSLATE_BRICK_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.DEEPSLATE_TILE_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.TUFF_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.POLISHED_TUFF_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.TUFF_BRICK_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.BRICK_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.MUD_BRICK_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.SANDSTONE_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.SMOOTH_SANDSTONE_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.CUT_SANDSTONE_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.RED_SANDSTONE_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.SMOOTH_RED_SANDSTONE_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.CUT_RED_SANDSTONE_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.PRISMARINE_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.PRISMARINE_BRICK_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.DARK_PRISMARINE_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.NETHER_BRICK_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.RED_NETHER_BRICK_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.BLACKSTONE_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.POLISHED_BLACKSTONE_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.POLISHED_BLACKSTONE_BRICK_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.END_STONE_BRICK_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.PURPUR_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.QUARTZ_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.SMOOTH_QUARTZ_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.CUT_COPPER_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.EXPOSED_CUT_COPPER_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.WEATHERED_CUT_COPPER_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.OXIDIZED_CUT_COPPER_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.WAXED_CUT_COPPER_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.WAXED_EXPOSED_CUT_COPPER_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.WAXED_WEATHERED_CUT_COPPER_VERTICAL_SLAB.get())
                .add(VerticalSlabBlocks.WAXED_OXIDIZED_CUT_COPPER_VERTICAL_SLAB.get());

        getOrCreateRawBuilder(BlockTags.MINEABLE_WITH_PICKAXE)
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.MOSSY_STONE_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.MOSSY_COBBLED_DEEPSLATE_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.MOSSY_DEEPSLATE_BRICK_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.MOSSY_DEEPSLATE_TILE_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.MOSSY_TUFF_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.MOSSY_TUFF_BRICK_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.MOSSY_BRICK_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.PALE_MOSSY_STONE_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.PALE_MOSSY_COBBLED_DEEPSLATE_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.PALE_MOSSY_DEEPSLATE_BRICK_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.PALE_MOSSY_DEEPSLATE_TILE_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.PALE_MOSSY_TUFF_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.PALE_MOSSY_TUFF_BRICK_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.PALE_MOSSY_BRICK_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.CRIMSON_MOSSY_STONE_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.CRIMSON_MOSSY_COBBLED_DEEPSLATE_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.CRIMSON_MOSSY_DEEPSLATE_BRICK_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.CRIMSON_MOSSY_DEEPSLATE_TILE_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.CRIMSON_MOSSY_TUFF_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.CRIMSON_MOSSY_TUFF_BRICK_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.CRIMSON_MOSSY_BRICK_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.WARPED_MOSSY_STONE_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.WARPED_MOSSY_COBBLED_DEEPSLATE_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.WARPED_MOSSY_DEEPSLATE_BRICK_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.WARPED_MOSSY_DEEPSLATE_TILE_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.WARPED_MOSSY_TUFF_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.WARPED_MOSSY_TUFF_BRICK_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.WARPED_MOSSY_BRICK_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.CUT_WHITE_SANDSTONE_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.SMOOTH_WHITE_SANDSTONE_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.WHITE_SANDSTONE_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.CUT_ORANGE_SANDSTONE_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.SMOOTH_ORANGE_SANDSTONE_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.ORANGE_SANDSTONE_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.CUT_BLACK_SANDSTONE_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.SMOOTH_BLACK_SANDSTONE_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.BLACK_SANDSTONE_VERTICAL_SLAB.get()))
                .addOptionalElement(getResourceLocationFromBlockRegistry(VerticalSlabBlocks.BRIMSTONE_BRICK_VERTICAL_SLAB.get()));
    }

    private ResourceLocation getResourceLocationFromBlockRegistry(Block block) {
        return BuiltInRegistries.BLOCK.getKey(block);
    }
}
